language: java
jdk:
  - oraclejdk8

env:
  - NODE_VERSION=8.10.0

script:
  - nvm install $NODE_VERSION
  - npm install
  - npm run downloadAntlr
  - pwd
  - npm run buildGrammar
  - ls -la src/**/*
  - npm run test